### ISSUE TITLE
Write HTML/CSS and replicate the given target image in the least code possible.

### ISSUE THREAD

**Issue by harshshukla07** [PEC-CSS/graveyard#26]
# CSS

![48](https://user-images.githubusercontent.com/107511647/221398707-695607d3-458c-4dd3-bf8d-570161e808fc.png)

```css
<div></div>
<style>
  div {
    width: 100px;
    height: 100px;
    background: #dd6b4d;
  }
</style>
```

`colors used: #293462 , #FE5F55 , #A64942`
